; Master ESP32 Controller
; Board: Generic ESP32 Dev Module
; Flash via USB — select correct COM port in VS Code bottom bar

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
src_dir = .

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
