"""remove_iot_sensor_readings

Revision ID: 1e7de45c5093
Revises: 0006_add_ocr_fields_to_gate_logs
Create Date: 2026-04-28 23:08:36.182152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e7de45c5093'
down_revision: Union[str, None] = '0006_add_ocr_fields_to_gate_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_iot_vehicle_recorded'), table_name='iot_sensor_readings')
    op.drop_table('iot_sensor_readings')
    op.execute("DROP TYPE iot_sensor_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ENGINE_TEMP', 'OIL_PRESSURE', 'BRAKE_PAD', 'BATTERY_VOLTAGE', name='iot_sensor_type').create(op.get_bind())
    op.create_table('iot_sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sensor_type', postgresql.ENUM('ENGINE_TEMP', 'OIL_PRESSURE', 'BRAKE_PAD', 'BATTERY_VOLTAGE', name='iot_sensor_type'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('iot_sensor_readings_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('iot_sensor_readings_pkey'))
    )
    op.create_index(op.f('idx_iot_vehicle_recorded'), 'iot_sensor_readings', ['vehicle_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###
