"""add device_logs table

Revision ID: f70cec14fbd8
Revises: 0009_drop_gps_speed_heading
Create Date: 2026-05-08 14:16:31.945103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70cec14fbd8'
down_revision: Union[str, None] = '0009_drop_gps_speed_heading'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_log_created', 'device_logs', ['created_at'], unique=False)
    op.create_index('idx_device_log_device', 'device_logs', ['device'], unique=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_break_logs_driver_shift_date'), table_name='break_logs')
    op.drop_index(op.f('ix_break_logs_driver_start_time'), table_name='break_logs')
    op.drop_index(op.f('ix_camera_readings_trip_id'), table_name='camera_readings')
    op.drop_index(op.f('ix_camera_readings_vehicle_created'), table_name='camera_readings')
    op.drop_index(op.f('ix_driver_exchanges_rotation_assignment_id'), table_name='driver_exchanges')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_gate_logs_created_at'), table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_plate_created'), table_name='gate_logs')
    op.drop_index(op.f('ix_maint_requests_status_created'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maint_requests_vehicle_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_status'), table_name='notifications')
    op.drop_index(op.f('ix_reroute_logs_driver_id'), table_name='reroute_logs')
    op.drop_index(op.f('ix_reroute_logs_status_requested'), table_name='reroute_logs')
    op.drop_index(op.f('ix_rotation_assignments_shift_date'), table_name='rotation_assignments')
    op.drop_index(op.f('ix_routes_is_active'), table_name='routes')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_trip_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_trip_status'), table_name='tickets')
    op.drop_index(op.f('uix_tickets_trip_seat'), table_name='tickets', postgresql_where='(seat_number IS NOT NULL)')
    op.drop_index(op.f('ix_trips_driver_scheduled'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_scheduled'), table_name='trips')
    op.drop_index(op.f('ix_trips_scheduled_start'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_status_scheduled'), table_name='trips')
    op.drop_index(op.f('ix_trips_vehicle_scheduled'), table_name='trips')
    op.drop_index(op.f('ix_users_role_is_active'), table_name='users')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_users_role_is_active'), 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_scheduled'), 'trips', ['vehicle_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_status_scheduled'), 'trips', ['status', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_scheduled_start'), 'trips', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_route_scheduled'), 'trips', ['route_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_driver_scheduled'), 'trips', ['driver_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('uix_tickets_trip_seat'), 'tickets', ['trip_id', 'seat_number'], unique=True, postgresql_where='(seat_number IS NOT NULL)')
    op.create_index(op.f('ix_tickets_trip_status'), 'tickets', ['trip_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_trip_id'), 'tickets', ['trip_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_routes_is_active'), 'routes', ['is_active'], unique=False)
    op.create_index(op.f('ix_rotation_assignments_shift_date'), 'rotation_assignments', ['shift_date'], unique=False)
    op.create_index(op.f('ix_reroute_logs_status_requested'), 'reroute_logs', ['status', 'requested_at'], unique=False)
    op.create_index(op.f('ix_reroute_logs_driver_id'), 'reroute_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_status'), 'notifications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_maint_requests_vehicle_id'), 'maintenance_requests', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_maint_requests_status_created'), 'maintenance_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_gate_logs_plate_created'), 'gate_logs', ['plate_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_gate_logs_created_at'), 'gate_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_index(op.f('ix_driver_exchanges_rotation_assignment_id'), 'driver_exchanges', ['rotation_assignment_id'], unique=False)
    op.create_index(op.f('ix_camera_readings_vehicle_created'), 'camera_readings', ['vehicle_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_camera_readings_trip_id'), 'camera_readings', ['trip_id'], unique=False)
    op.create_index(op.f('ix_break_logs_driver_start_time'), 'break_logs', ['driver_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_break_logs_driver_shift_date'), 'break_logs', ['driver_id', 'shift_date'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_created'), 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_index('idx_device_log_device', table_name='device_logs')
    op.drop_index('idx_device_log_created', table_name='device_logs')
    op.drop_table('device_logs')
    # ### end Alembic commands ###
